### ISSUE TITLE
Snippet "prefix" convetions

### ISSUE THREAD

**Issue by hhkaos** [Esri/arcgis-js-vscode-snippets#10]
I see there are many acronyms `sms`, `sls`, `sfs`, ... I think it would be also nice to add the extended version for developers not so familiar with our acronyms, something like `SimpleMarkerSymbol (sms)`:

```js
{
"SimpleMarkerSymbol": {
    "body": [
      "{",
      "\ttype: \"simple-marker\",",
      "\tcolor: [255, 255, 255, 0.25],",
      "\tsize: 12,",
      "\tstyle: \"${1|circle,square,cross,x,diamond,triangle,path|}\",",
      "\toutline: {",
      "\t\twidth: 1,",
      "\t\tcolor: [255, 255, 255, 1]",
      "\t}",
      "}"
    ],
    "description": "Create a SimpleMarkerSymbol",
    "prefix": "SimpleMarkerSymbol (sms)"
  },
```

This way it still matches with `sms`, but also with `sym`, `marke`, ...:

![Screenshot 2021-06-16 at 17 40 33](https://user-images.githubusercontent.com/826965/122250685-28e8e780-ceca-11eb-9a48-bc179f04fab7.png)
![Screenshot 2021-06-16 at 17 40 42](https://user-images.githubusercontent.com/826965/122250700-2ab2ab00-ceca-11eb-9b5a-7d8aa46ac4e1.png)
![Screenshot 2021-06-16 at 17 41 07](https://user-images.githubusercontent.com/826965/122250708-2d150500-ceca-11eb-8423-4bbf04683f05.png)

**Update**: [This has been added to the description](https://github.com/hhkaos/arcgis-js-vscode-snippets/commit/a507760aa7a77f161078d081be4a18a8044bff56)
~~I would also add in the name, the path to classes. Instead of just `SimpleMarkerSymbol` use `symbols/SimpleMarkerSymbol`:~~
...

Does any of these ideas make sense to you? 😄

**Comment by kellyhutchins** [comment]
I understand the bit about changing the prefix to be the full name - that makes sense. But I don't understand the part about adding the path (symbols/SimpleMarkerSymbol)?

**Comment by hhkaos** [comment]
Yes, maybe SimpleMarkerSymbols wasn't the best example. I was thinking of snippets like `map`, `webmap`, `webscene`, `labeling2d` and `labeling3d', which return a snippet with a `new Class`:

```
"CreateMap": {
    "body": [
      "var map = new Map({",
      "\tbasemap: \"${1:streets}\"",
      "});",
      "var view = new MapView({",
      "\tcontainer:${2:\"viewDiv\"},",
      "\tmap:map,",
      "\tzoom: ${3: 4},",
      "\tcenter:${4:[15,65]}",
      "});"
    ],
    "description": "Create map and map view",
    "prefix": "map"
  },
```

On snippets like this, you might need to add an element to the `require` function to load the class. So in order to save the developer to go to the developer site and search for the path to that class, I was thinking that it might be useful to it somewhere in VS Code. It might be also in the description.

Does it make sense to add a suffix to every ArcGIS-related snippet is clearly different from all the other autocompletion?

**Comment by kellyhutchins** [comment]
@hhkaos  ok now I see what you mean. Yes I think it might be good to include the path. I'll look into adding it for the existing snippets and play around with it for a day and see how it feels to use the snippets.

**Comment by kellyhutchins** [comment]
I looked at adding the path but I'm not sure yet where the best spot to add it would be. I did some testing but want to do some more research to see if I can find some best practices info. I did update the prefix to use the longer names.

**Comment by hhkaos** [comment]
Hi Kelly, thanks for the update!.

I have been thinking about this, and maybe it is enough just to add the path to the module in the description. What do you think about that?

While doing the [cheatsheet](https://github.com/Esri/arcgis-js-vscode-snippets/issues/11) & [snippets builder](https://github.com/Esri/arcgis-js-vscode-snippets/issues/14) I realized that having a "Checklist" with all the conventions would be awesome.  I have seen quite a bit of heterogeneity in the way snippets are written/named/described, so I think it would be very helpful in order to make this repo grow properly. Does it make sense? 

If you think it makes sense I would open an issue for each field (prefix conventions, body conventions, ...) to brainstorm and discuss the best way to define each one, and have a place refer in the contributing white but also to revisit for enhancements if needed in the future.

**Comment by RalucaNicola** [comment]
So I guess with the convention that in JavaScript we use autocasting as much as possible, then the problem of importing is not so dramatic. And in TypeScript you can easily use autoimports...

But I see what you mean, I always have to go to the doc to figure out where that LabelClass is placed :D And I think you said you'd like to add class imports for JavaScript as well, so then people will really have to make a lot of imports.
