### ISSUE TITLE
Add Snippets builder to enhance the contribution experience

### ISSUE THREAD

**Issue by hhkaos** [Esri/arcgis-js-vscode-snippets#14]
Hello again!,

I wanted to share [a simple interface I have built for myself to help me create new snippets](https://hhkaos.github.io/vscode-snippets-builder/). While I was doing it, I decided to make it public just in case it could help other developers too (for personal use or to contribute to this repo). 

So I just wanted to share it with you:

[![VS Code snippets builder](https://github.com/hhkaos/vscode-snippets-builder/raw/main/assets/screenshot.png)](https://hhkaos.github.io/vscode-snippets-builder/)

If you think it can make sense to host the app on this repo, I can finish/clean it a little, remove my repo and do a pull request to this one.

Cheers!

**Comment by hhkaos** [comment]
I just saw [this](https://snippet-generator.app/)! 😅 🤣 , well, at least this allows the developer to open an issue 😉 xD

**Comment by kellyhutchins** [comment]
I like the custom snippet builder you created and think the option to allow developers to open an issue is useful. I also like that you can add custom tips etc to help users create snippets that fit in with the standards we define. I think it'd be great to include in this repo.

**Comment by hhkaos** [comment]
Awesome!, I guess we should do it after we finish discussing the conventions, right? (this way the custom tips would be more accurate).

**Comment by hhkaos** [comment]
Done: https://github.com/Esri/arcgis-js-vscode-snippets/pull/25
