### ISSUE TITLE
Snippet proposal: Find a layer by it's name

### ISSUE THREAD

**Issue by hhkaos** [Esri/arcgis-js-vscode-snippets#16]
I took the idea from [this script](https://github.com/esrinederland/CoolScripts/tree/main/FindLayer) that Maarten from Esri Netherlands published on its [CoolScripts](https://github.com/esrinederland/CoolScripts) repo.

---

**Prefix**: findLayer
**Description**: 
**Snippet**:

```js
const fl = view.map.layers.find( l => l.title === "${1:LayerTitle}");
```

Code:
```js
"Find a layer by it's name": {
    "prefix": "findLayer",
    "body": [
	"const fl = view.map.layers.find( l => l.title === \"${1:LayerTitle}\");",
    ],
    "description": ""
}
```

**Comment by kellyhutchins** [comment]
This looks like a useful snippet. We'll just want to remove the const fl to fit with the standards we discussed earlier.

**Comment by hhkaos** [comment]
Yep!, you are right!

**Comment by RalucaNicola** [comment]
useful indeed!

so only `view.map.layers.find( l => l.title === "${1:LayerTitle}");` with the prefix `findLayer` sounds great to me

**Comment by hhkaos** [comment]
PR done!
