### ISSUE TITLE
Unknown language 

### ISSUE THREAD

**Issue by gavinr** [Esri/arcgis-js-vscode-snippets#2]
If I  go to "Help > Toggle Developer Tools" and then open up a VS code project and then open `package.json`, I see this error:

```
[Esri.arcgis-jsapi-snippets]: Unknown language in `contributes.arcgis-jsapi-snippets.language`. Provided value: typesccript
```

**Comment by kellyhutchins** [comment]
Checked in a fix for this and will push the updates out to the marketplace

**Comment by gavinr** [comment]
Thanks!
