### ISSUE TITLE
Snippet "description" conventions

### ISSUE THREAD

**Issue by hhkaos** [Esri/arcgis-js-vscode-snippets#21]
Which should be the conventions about the snippet description?

![2021-08-05_11-49-54](https://user-images.githubusercontent.com/826965/128333456-fdd9bb34-2c10-487e-a665-d9cd831c6b8d.png)

<img width="972" alt="Screenshot 2021-08-05 at 12 14 16" src="https://user-images.githubusercontent.com/826965/128333569-e773ef65-3daf-4cbd-b5fc-b1ecd6cd372f.png">

Ideas/questions about how description should be defined:

* **Q1: It should be a proper description of what the snippet does, right?**<br>A: I would say yes, and reuse text from the API reference whenever possible.

* **Q2: If it is a snippet related to a class/module, do we recommend including the path to it?**<br>A: I would say yes (for now, the AMD Module path), but at the end probably, something like:  `Convert a geometry from Web Mercator units (wkid: 3857) to geographic units (wkid: 4326). Uses: esri/geometry/support/webMercatorUtils`.

**Comment by kellyhutchins** [comment]
I think yes to both Q1 and Q2 but for Q2 I think if we are going to include the path we should try to come up with an approach to include both AMD and ESM.  @andygup  do you know if we have info on the # of ESM vs AMD users?

**Comment by andygup** [comment]
Agreed, it would be good to include both AMD and ESM. 

> do you know if we have info on the # of ESM vs AMD users?

We are fairly certain that AMD users significantly outnumber ESM users. I can share what number we look at via an internal-only conversation if you want more info.

**Comment by kellyhutchins** [comment]
@andygup  got it. Ok then we can just do amd paths for now and add in (or switch to ESM) at some point in the future.

**Comment by andygup** [comment]
Oh sorry, I meant I do think we should include both AMD and ESM today and not wait.

One primary pain point for developers using ESM (also speaking for myself 😄 ) is translating AMD module paths, SDK samples and snippets to ESM.
