### ISSUE TITLE
Programmatically create UI/cheat sheet to explore snippets

### ISSUE THREAD

**Issue by hhkaos** [Esri/arcgis-js-vscode-snippets#32]
## Problem
As I mentioned in the [Snippet cheatsheet issue](https://github.com/Esri/arcgis-js-vscode-snippets/issues/11#issuecomment-888898903). Maintain the [table of snippets available](https://github.com/Esri/arcgis-js-vscode-snippets#snippets-available) **manually** is:

* It is more time-consuming:
   * Require an additional check on every PR to ensure the entry has been added in the table
   * Require contributors to modify the readme
* Prone to error/inconsistencies:
	* Mismatch between: prefixes and descriptions (table and snippets file)
* Not very usable:
	* The table is not intuitive to explore, even in alphabetical order (other [programming cheat sheets](https://www.google.com/search?q=cheatsheet+programming) group snippets, and use multiple columns). This affect users, but also for maintainers/contributors trying to understand if a code snippet already exists.

This also apply to [the one I made with cheatography.com](https://cheatography.com/hhkaos/cheat-sheets/vscode-arcgis-js-api-4-x-snippets-cheat-sheet/). But I think is worth to have a mechanism that can ensure it is always updated.

## Proposal
I think making a web interface should be pretty simple. I have been testing, and I think we can add "custom properties" to the custom snippets:
![2023-09-26_12-40-35](https://github.com/Esri/arcgis-js-vscode-snippets/assets/826965/b1aa05d1-c8d6-41ea-8805-9b9598e166cc)

That, way we could create properties like:
* `category`: To be able to group snippets (we could consider subcategories if needed; e.g. using a delimitation character)
*  `url`: if we want to add additional hyperlinks on each snippets. For example, we could add to help build an interface which in addition to showing the snippets, also add a link to a reference page:
	*  [colorVar snippet](https://github.com/hhkaos/arcgis-js-vscode-snippets/blob/9403ba4817eb8fefceb27ef635f0f339353e828d/snippets/javascript.json#L70C4-L70C23) could point to [ColorVariable class - API reference](https://developers.arcgis.com/javascript/latest/api-reference/esri-renderers-visualVariables-ColorVariable.html) 
	* Or a [dojoConfig snippet](https://github.com/hhkaos/esri-vscode-snippets/blob/fc2f9c99f4a5e2fdaf54dcacfd5706f6a4da6ac8/javascript.json.code-snippets#L29) to [Configure AMD to load custom modules](https://developers.arcgis.com/javascript/latest/amd-build/#configure-amd-to-load-custom-modules)
	* Or a [basemapStyle](https://github.com/hhkaos/arcgis-js-vscode-snippets/blob/9403ba4817eb8fefceb27ef635f0f339353e828d/snippets/javascript.json#L355) to [Map class - API Reference > Basemap](https://developers.arcgis.com/javascript/latest/api-reference/esri-Map.html#basemap)
	* etc.

What do you think? I envision something a simple serverless SPA, like this:

<img width="1010" alt="Screenshot 2023-09-26 at 14 18 41" src="https://github.com/Esri/arcgis-js-vscode-snippets/assets/826965/1edb489a-8428-48af-b7a2-117867eb0eb1">

**Comment by kellyhutchins** [comment]
Sounds awesome!
