### ISSUE TITLE
Add snippets for Search widget (different configurations)

### ISSUE THREAD

**Issue by hhkaos** [Esri/arcgis-js-vscode-snippets#44]
The JS [Search Widget](https://developers.arcgis.com/javascript/latest/api-reference/esri-widgets-Search.html) has many optional properties and different source options.

Create a snippet for each scenario below:
- [ ] Search [widget](https://developers.arcgis.com/javascript/latest/sample-code/widgets-search-3d/)
- [ ] Search widget with [multiple sources](https://developers.arcgis.com/javascript/latest/sample-code/widgets-search-multiplesource/)
- [ ] Search widget with [custom source](https://developers.arcgis.com/javascript/latest/sample-code/widgets-search-customsource/)

**Comment by nooras** [comment]
hey @hhkaos 
Is it open ? I want to take it. Kindle please assign me.
Doubt:
where to add those snippets?

**Comment by hhkaos** [comment]
Hi @nooras ! yes it is! 😄 

Those snippets would go here: https://github.com/Esri/arcgis-js-vscode-snippets/blob/master/snippets/javascript.json

I gues you have seen the [contributing.md](https://github.com/Esri/arcgis-js-vscode-snippets/blob/master/CONTRIBUTING.md), but just in case, there you have some [additional info about JS and TS snippets](https://github.com/Esri/arcgis-js-vscode-snippets/blob/master/CONTRIBUTING.md#javascript-and-typescript-snippets)

**Comment by nooras** [comment]
Hi @hhkaos 
Have a small doubt 
Some search widget snippet are present over here [cyatteau/arcgis-js-vscode-snippets](https://github.com/cyatteau/arcgis-js-vscode-snippets) as per above commit.
Similarly need to add snippets for below 3 in [esri /arcgis-js-vscode-snippets](https://github.com/Esri/arcgis-js-vscode-snippets) project?
- Search [widget](https://developers.arcgis.com/javascript/latest/sample-code/widgets-search-3d/)
- Search widget with [multiple sources](https://developers.arcgis.com/javascript/latest/sample-code/widgets-search-multiplesource/)
- Search widget with [custom source](https://developers.arcgis.com/javascript/latest/sample-code/widgets-search-customsource/)

Correct me if i am wrong!

**Comment by nooras** [comment]
hi @hhkaos 
Have raised a PR #55 
Kindly please check it

**Comment by hhkaos** [comment]
I'll take a look later today! Thanks @nooras !

**Comment by hhkaos** [comment]
Awesome @nooras !! Thank you very much for your help solving this!

**Comment by nooras** [comment]
> Awesome @nooras !! Thank you very much for your help solving this!

Thank you to give me a chance to contribute in this project.
Love to contribute during / after hacktoberfest
