### ISSUE TITLE
Enhance snippets builder

### ISSUE THREAD

**Issue by hhkaos** [Esri/arcgis-js-vscode-snippets#46]
I think we can improve the [snippet builder](https://esri.github.io/arcgis-js-vscode-snippets/builder/) by:

* [ ] Increase height of body and description fields (calcite)
* [ ] Adding checkboxes to be able to select the [language **snippet scope**](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-scope). It should include the following [language identifiers](https://code.visualstudio.com/docs/languages/identifiers#_known-language-identifiers): javascript (JavaScript), json (JSON), css (CSS), html (HTML), scss (SCSS), typescript (TypeScript), typescriptreact (TypeScrip JSX).
* [ ] Been able to copy generated snippet to clipboard using a copy-to-clipboard button
* [ ] Add button to import snippet (form VS Code)

**Comment by BochaberiDaisy** [comment]
Hi @hhkaos 
Please assign me this issue

**Comment by hhkaos** [comment]
Thanks @BochaberiDaisy !! Done! 😄

**Comment by BochaberiDaisy** [comment]
Right, that would be enough. 

Thank you for pointing out the Calcite version update. I'll update to the latest version.

**Comment by hhkaos** [comment]
Awesome, thanks! :)

**Comment by hhkaos** [comment]
Sorry @BochaberiDaisy I had some personal issues I had to handle.

I just checked, and it looks very good!

I'm going to add a few comments to the PR :)
