### ISSUE TITLE
Cheatsheet fails loading on gh-pages

### ISSUE THREAD

**Issue by hhkaos** [Esri/arcgis-js-vscode-snippets#54]
The cheatsheet is not properly loading due to an incorrect path (404): [check](https://esri.github.io/arcgis-js-vscode-snippets/cheatsheet/)
![Screenshot 2024-10-04 at 17 36 50](https://github.com/user-attachments/assets/31dd881d-4c28-4c47-ae52-fd4bee5efca7)

We need to fix that.

**Comment by nooras** [comment]
Hi @hhkaos 
Can you please assign me this issue ?

**Comment by cyatteau** [comment]
> Hi @hhkaos Can you please assign me this issue ?

Hi @nooras! You're welcome to work on this issue, but per the rules, you can only earn points for one issue labeled as "good first issue" toward the Developer Summit prizes for Hacktoberfest. If your PR on [this issue](https://github.com/Esri/arcgis-js-vscode-snippets/issues/44) is accepted, you’ll receive points for that, but that's the only 'good first issue' you can earn points on. If you still want to work on this one, we’ll assign it to you. Feel free to check out "help wanted" issues for more opportunities!

You can find the official rules [here](https://www.esri.com/arcgis-blog/wp-content/uploads/2024/10/2024-Esri-Hacktoberfest-Contest-Official-Rules-2.pdf). If you have any questions, let us know!

Thanks and happy coding! 😊

**Comment by hhkaos** [comment]
@nooras, so you still want to do it? I mean, even if you don't get points for the prize? If you are OK, I'll gladly assign it to you 😄

**Comment by nooras** [comment]
Yes @hhkaos i would like to take this issue
Also i have a doubt where can i find steps to start a local server ?

**Comment by hhkaos** [comment]
That's a good question!!,

We didn't add that to the CONTRUBUTING.md file!, I'll create an issue and add that to me.

For now, you can see the [package.json file](https://github.com/Esri/arcgis-js-vscode-snippets/blob/master/cheatsheet/package.json) that lists three commands:

`npm run dev`
`npm run build`
`npm run preview`

I hope that helps! :)

**Comment by nooras** [comment]
@hhkaos 
It works fine in local
Is the issue in deployed site ? how should i fix it? any suggestion?
![image](https://github.com/user-attachments/assets/507ae82b-d348-469f-99e3-de3e0a367c40)

**Comment by hhkaos** [comment]
Sorry @nooras, I was out with my family over the weekend.

The problem is with the built version. 

So you will have to:
* Create a vite.config.js and set the ["base" parameter properly](https://v2.vitejs.dev/config/#base)
* You will probably need to change some paths in the index.html
* And uncomment the [.gitignore](https://github.com/Esri/arcgis-js-vscode-snippets/blob/master/cheatsheet/.gitignore#L11) because the app should be loaded at https://esri.github.io/arcgis-js-vscode-snippets/cheatsheet/dist, not at https://esri.github.io/arcgis-js-vscode-snippets/cheatsheet (which is the development version)

I hope this helps!

Good luck :)

**Comment by nooras** [comment]
> Sorry @nooras, I was out with my family over the weekend.
> 
> The problem is with the built version.
> 
> So you will have to:
> 
> * Create a vite.config.js and set the ["base" parameter properly](https://v2.vitejs.dev/config/#base)
> * You will probably need to change some paths in the index.html
> * And uncomment the [.gitignore](https://github.com/Esri/arcgis-js-vscode-snippets/blob/master/cheatsheet/.gitignore#L11) because the app should be loaded at https://esri.github.io/arcgis-js-vscode-snippets/cheatsheet/dist, not at https://esri.github.io/arcgis-js-vscode-snippets/cheatsheet (which is the development version)
> 
> I hope this helps!
> 
> Good luck :)

Thanks for your help
But i have a small doubt. Point 3 there is nothing to uncomment in .gitignore. U mean need to comment dist ? @hhkaos

**Comment by hhkaos** [comment]
Ouch, yes, sorry.

You need to **remove** `dist` from .gitignore, because we want the app to be available on GitHub pages, so the built version needs to be uploaded to the repo.

**Comment by hhkaos** [comment]
It's now working! https://esri.github.io/arcgis-js-vscode-snippets/cheatsheet/dist/
