### ISSUE TITLE
Contributing guidelines

### ISSUE THREAD

**Issue by hhkaos** [Esri/arcgis-js-vscode-snippets#7]
First of all, congrats for this awesome repository :), I would love to contribute but I have no previous experience developing VSCode extensions.

I'm using a Mac, so I have modified the file at ' ~/.vscode/extensions/esri.arcgis-jsapi-snippets-1.1.2/snippets/javascript.json' but I don't know how I can test if it's properly working. How do I do it? Do I need to refresh/reload the extension?

Thanks!!

> Note: I would be nice to include the readme / contributing.md simple instructions on how to do it.

**Comment by hhkaos** [comment]
I just found that adding a "prefix" and with Cmd+Shift+P -> "Developer: Reload Window" just works :)

**Comment by hhkaos** [comment]
One question, do you think it could make sense to add the following resources to the [contributing.md](https://github.com/Esri/arcgis-js-vscode-snippets/blob/master/contributing.md):

- [Snippets in Visual Studio Code](https://code.visualstudio.com/docs/editor/userdefinedsnippets)
- [Your First Extension | Visual Studio Code Extension API](https://code.visualstudio.com/api/get-started/your-first-extension)
- [JS IntelliSense in VSCode](https://code.visualstudio.com/docs/languages/javascript#_intellisense)
- [IntelliSense in VSCode](https://code.visualstudio.com/docs/languages/javascript#_intellisense)

I would be welcome to add a PR if you think so :).

// cc: @RalucaNicola, @andygup , @kellyhutchins, @ekenes

**Comment by RalucaNicola** [comment]
that sounds like a good idea to me!

**Comment by hhkaos** [comment]
Great, I'll add it then 😄 .

One more question, **do you recommend me to link then snippets in the `~/.vscode/extensions` with the snippets on this repo?, or do you just use a developer version of the snippet in local to avoid conflicts?**

**Comment by RalucaNicola** [comment]
my workflow is usually to test them locally, just by adding them to the user snippets files (Cmd + P >Preferences: Configure user snippets, pick the language and add the snippet in there. If it's good, then I add it to this repo and I check it out once it's published. Then I usually remove the snippets from the local file.

I am not very proficient in this though, so there are for sure better ways to test the snippets before adding them to production.

**Comment by hhkaos** [comment]
Cool! I didn't know about the "Cmd + P >Preferences: Configure user snippets" either! 😅 , that another easy way to test snippets 👍 .

Anyway, I have also to install the VSIX from local (thinking that it might link the original folder):
![Screenshot 2021-06-16 at 16 19 34](https://user-images.githubusercontent.com/826965/122236247-a4dd3280-cebe-11eb-9fb6-64213286b31d.png)

But it makes a copy of the folder, then ask me to update to 1.1.2 and do another copy:
![Screenshot 2021-06-16 at 16 21 13](https://user-images.githubusercontent.com/826965/122236579-ed94eb80-cebe-11eb-84fd-ff6f796935f6.png)

And of course, none of those folders are identical to the original, so... I will wait for @kellyhutchins 😄 .

Thanks one more time!!

**Comment by kellyhutchins** [comment]
I always test snippets locally using the same steps as Raluca outlines above. Installing from .vsix is just another way to install the existing published extension. 
I will work on updating and publishing the updated extension to marketplace this week. Thanks for your contributions!

**Comment by hhkaos** [comment]
Thank you! I just did my PR so I'm going to close this 😉
